<Error>:
    BoxLayout:
        orientation: 'vertical'

        Label:


        MDRoundFlatIconButton:
            icon: "account-alert-outline"
            text: "         בוש הסנ"
            font_name:'Arial.ttf'
            text_color: 0.7764705882, 0, 0, 1
            line_color:0.7764705882, 0, 0, 1
            icon_color: 0.7764705882, 0, 0, 1
            size_hint_x:0.5
            pos_hint :{'x':.25, 'y':.2}
            on_press: root.reconnect()

        Label:
